<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="47" started-at="2019-03-18T04:09:00Z" finished-at="2019-03-18T04:09:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="47" started-at="2019-03-18T04:09:00Z" finished-at="2019-03-18T04:09:00Z">
      <class name="tests.LoginTest">
        <test-method status="FAIL" signature="setupEnvironment()[pri:0, instance:tests.LoginTest@1150435]" name="setupEnvironment" is-config="true" duration-ms="0" started-at="2019-03-18T09:39:00Z" finished-at="2019-03-18T09:39:00Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at java.util.Hashtable.put(Unknown Source)
	at java.util.Properties.setProperty(Unknown Source)
	at java.lang.System.setProperty(Unknown Source)
	at tests.AbstractTest.setupEnvironment(AbstractTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupEnvironment -->
        <test-method status="SKIP" signature="closeEnvironment()[pri:0, instance:tests.LoginTest@1150435]" name="closeEnvironment" is-config="true" duration-ms="0" started-at="2019-03-18T09:39:00Z" finished-at="2019-03-18T09:39:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeEnvironment -->
        <test-method status="SKIP" signature="verifyLogin()[pri:0, instance:tests.LoginTest@1150435]" name="verifyLogin" duration-ms="0" started-at="2019-03-18T09:39:00Z" finished-at="2019-03-18T09:39:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
